CREATE TABLE USUARIO(
	IDUsuario INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	IDTipoUsuario INT NOT NULL,
	nome NVARCHAR (15) NOT NULL,
	senha NVARCHAR (15) NOT NULL,
	email NVARCHAR (30) NOT NULL,
	 FOREIGN KEY (IDTipoUsuario) REFERENCES TIPO_USUARIO(IDTipoUsuario)

)
drop table USUARIO


CREATE TABLE TIPO_USUARIO(
	IDTipoUsuario INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	tipo NVARCHAR(20) NOT NULL


--inner join USUARIO COM TIPO USUARIO
select nome as [NOME DO USUARIO],
		TIPO_USUARIO.tipo as [NIVEL DE ACESSO],
		USUARIO.senha as [SENHA DO USUARIO],
		USUARIO.email as EMAIL
from USUARIO
inner join TIPO_USUARIO on USUARIO.IDTipoUsuario = TIPO_USUARIO.IDTipoUsuario
)